### ISSUE TITLE
Should this repo be closed? 

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/ns-3-dev-git#15]
Should this repo be inactivated/closed now that the ns3-module repo is active?

**Comment by nightlark** [comment]
The repo that it was forked from is also no longer getting updated as an ns-3 mirror.

**Comment by trevorhardy** [comment]
I think we can close this one out as Ryan moved the ns-3 HELICS stuff as its own repo that you semi-manually put into your existing ns-3 source structure.

**Comment by nightlark** [comment]
If there aren't any objections, I'll archive the repository.
